In [18]:
from XQuant import BackTestRunner, BackTestOptions, BARRA
from XQuant import Strategy, DataAPI, Config, Tools, DataReady
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [15]:
X = np.arange(8).reshape(4,-1)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
y = np.arange(24).reshape(4, -1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
model = sm.WLS(endog=y, exog=X)
result = model.fit()

In [21]:
result.params

array([[ 3.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        -3.49720253e-15, -1.00000000e+00, -2.00000000e+00],
       [ 1.66533454e-16,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00,  5.00000000e+00]])